[versions]
kotlin = "2.3.10"
dokka = "2.1.0"
jgitver = "0.10.0-rc03"
nexusPublish = "2.0.0"
ksp = "2.3.5"
kotlinPoet = "2.2.0"
kotlinBard = "0.6.0"
compileTesting = "0.12.1"
junit = "6.0.2"
strikt = "0.35.1"
intellijPlugin = "2.11.0"
intellijIdea = "2025.3"
kotlinx-serialization = "1.10.0"
kotlinter = "5.4.0"

[plugins]
intellijPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlugin" }

[libraries]
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradle = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }
kotlinpoet-metadata = { module = "com.squareup:kotlinpoet-metadata", version.ref = "kotlinPoet" }
kotlinbard = { module = "com.faendir:kotlinbard", version.ref = "kotlinBard" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka" }
jgitver = { module = "gradle.plugin.fr.brouillard.oss.gradle:gradle-jgitver-plugin", version.ref = "jgitver" }
nexusPublish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexusPublish" }
junit = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
kotlin-compileTesting = { module = "dev.zacsweers.kctfork:ksp", version.ref = "compileTesting" }
strikt = { module = "io.strikt:strikt-core", version.ref = "strikt" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinter-gradle = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }
